config/routes.rb
Rails.application.routes.draw do

devise_for :users
root to: "homes#top"

get "/home/about" => "homes#about", as: "about"

resources :users, only: [:new, :create, :index, :show, :edit, :update]

resources :books, only: [:index, :show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    new_user_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if user_signed_in? %>
      <li>
        <%= link_to "Home", new_user_path %>
      </li>
      <li>
        <%= link_to "Users", users_path %>
      </li>
      <li>
        <%= link_to "Books", books_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", user_session_path %>
      </li>
    <% end %>
    <%= yield %>
  </body>
</html>